### ISSUE TITLE
can't start any process

### ISSUE THREAD

**Issue by VitaliyAT** [chebum/Supervisor#2] opened 2021-07-31 06:02 UTC
```
Необработанное исключение: System.ArgumentOutOfRangeException: Длина не может быть меньше нуля.
Имя параметра: length
   в System.String.Substring(Int32 startIndex, Int32 length)
   в Supervisor.Program.ParseArgs(String[] args)
   в Supervisor.Program.Main(String[] args)
```
Normally need guard for rerun gui program as administrator.

**Comment by chebum** [comment] 2021-08-01 13:38
It seems to be a duplicate of https://github.com/chebum/Supervisor/issues/1

**Closed as completed by chebum** 2021-08-01 13:38 UTC
